[book]
title = "Basic Geometry"
authors = ["Suvabrata Chowdhury"]
language = "en"

[output.html]
git-repository-url = "https://github.com/SuvabrataChowdhury/basic-geometry-notes"
mathjax-support = false
smart-punctuation = false
theme = "src/theme"
